broker:
  image: eclipse-mosquitto
  ports:
    - 1883:1883
    - 9001:9001
  tty: true
  volumes:
    - ./mosquitto/:/mosquitto/

gateway:
  build: ./dockerfiles/paho_mqttsn/
  container_name: mqttsn_gateway
  ports:
    - 1883:1883/udp
    - 3881:3881/udp
  tty: true
  volumes:
    - ./paho_mqttsn/:/paho_mqttsn/
  command: MQTT-SNGateway -f /paho_mqttsn/config/gateway.conf
  links:
    - broker

